#If true the plugin uses the Vault integration if installed
economyEnabled: false
#Price that a disenchant cost with the Vault integration
disenchantPrice: 15
#If the Vault integration is disabled, use this material as payment. Note: If bad format or material not found, the plugin uses the default (DIAMOND)
materialPayment: DIAMOND
#Custom price for material-based payments. If its < 0 the plugin will use the default values (1 for enchantment level + 1)
materialCustomPrice:
  basePrice: -1
  #Per level price enchantment
  perLevelPrice: -1
messages:
  #Selected language
  language: eng
  eng:
    EnchantmentExtractionSuccess: Enchantments extracted!
    NoEnchantmentExtracted: No enchantments were extracted. Check if you have enough material/money for it!
    SomeEnchantmentExtracted: Some enchantments were not extracted! Do you have enough material/money?
    NoEnchantmentInItem: The current item doesn't have any enchantment!
    NoPermissionMessage: You dont have permissions to use this command!
    ConsoleError: This is not a console command!
    UpdateAvailableMessage: There is a new update available.
    NoUpdateAvailableMessage: There is not a new update available.
    InvalidEnchantmentLevel: Invalid enchantment level (Are you disenchanting vanilla enchantments?)
    InvalidMaterialError: The provided material payment is not valid, defaulting to diamonds
  esp:
    EnchantmentExtractionSuccess: Encantamientos extraidos!
    NoEnchantmentExtracted: No se han podido extraer todos los encantamientos. Tienes suficientes materiales/dinero para ello?
    SomeEnchantmentExtracted: No se han podido extraer algunos encantamientos. Tienes suficientes materiales/dinero para ello?
    NoEnchantmentInItem: Este objeto no tiene ningun encantamiento!
    NoPermissionMessage: No tienes permiso para usar este comando!
    ConsoleError: No es un comando de consola!
    UpdateAvailableMessage: Hay una actualizacion disponible
    NoUpdateAvailableMessage: No hay actualizaciones disponibles
    InvalidEnchantmentLevel: Nivel de encantamiento invalido. ¿Estás desencantando encantamientos vanilla?
    InvalidMaterialError: El material indicado no es válido, usando diamantes...