name: EnchantmentsExtractor
version: "1.4"
main: com.alexthecaster.EnchantmentsExtractor.Main.Main
commands:
  disenchant:
    description: Command for disenchanting the item in your hand
    usage: /disenchant
permissions:
  enchantmentsextractor.disenchant:
    description: Permission that allows the player to use the disenchant command
softdepend: [Vault]